### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by KonstantinusPrime** [reahly/mono-external-lib#1]
1.) would it be possible to avoid plain strings in memory like "Assembly-CSharp" etc?
2.) how does your read_widechar function look?
3.) how does your utf8_to_utf16 function look?

I tried to get it working altough whenever I tried to use any function like find_class it would crash my program, i've set the base address for mono-2.0-bdwgc.dll using my driver fine.

thanks very much this is a great repo!

**Comment by reahly** [comment]
added the missing functions. if you want to hide strings in plain memory you could hash class names field names etc and to lookup hash the string you want to search with the same algorithm of course

**Comment by KonstantinusPrime** [comment]
thanks!
do you have an example for the implementation of hash? I saw your post on UC uses HASH_ already

**Comment by reahly** [comment]
well i mainly use it for speed, but that's off-topic and basic programming knowledge so i will close this
